"""Add CSV import support with manual accounts and import batches

Revision ID: d14df1218d8f
Revises: 7f3c1d9b9a9a
Create Date: 2025-12-21 14:06:15.998053

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd14df1218d8f'
down_revision = '7f3c1d9b9a9a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('import_batches',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('account_id', sa.String(length=255), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('filename', sa.String(length=512), nullable=False),
    sa.Column('bank_name', sa.String(length=255), nullable=True),
    sa.Column('transaction_count', sa.Integer(), nullable=False),
    sa.Column('imported_count', sa.Integer(), nullable=False),
    sa.Column('duplicate_count', sa.Integer(), nullable=False),
    sa.Column('error_count', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('error_details', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_import_batches_account', 'import_batches', ['account_id'], unique=False)
    op.create_index(op.f('ix_import_batches_account_id'), 'import_batches', ['account_id'], unique=False)
    op.create_index('ix_import_batches_user', 'import_batches', ['user_id'], unique=False)
    op.create_index(op.f('ix_import_batches_user_id'), 'import_batches', ['user_id'], unique=False)
    op.create_table('imported_transactions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('batch_id', sa.String(length=36), nullable=False),
    sa.Column('transaction_id', sa.String(length=36), nullable=False),
    sa.Column('original_id', sa.String(length=255), nullable=True),
    sa.Column('row_number', sa.Integer(), nullable=True),
    sa.Column('is_duplicate', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['import_batches.id'], ),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_imported_transactions_batch_id'), 'imported_transactions', ['batch_id'], unique=False)
    op.create_index(op.f('ix_imported_transactions_transaction_id'), 'imported_transactions', ['transaction_id'], unique=False)
    op.add_column('accounts', sa.Column('source_type', sa.String(length=50), nullable=False, server_default='api'))
    op.alter_column('accounts', 'requisition_id',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('accounts', 'requisition_id',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.drop_column('accounts', 'source_type')
    op.drop_index(op.f('ix_imported_transactions_transaction_id'), table_name='imported_transactions')
    op.drop_index(op.f('ix_imported_transactions_batch_id'), table_name='imported_transactions')
    op.drop_table('imported_transactions')
    op.drop_index(op.f('ix_import_batches_user_id'), table_name='import_batches')
    op.drop_index('ix_import_batches_user', table_name='import_batches')
    op.drop_index(op.f('ix_import_batches_account_id'), table_name='import_batches')
    op.drop_index('ix_import_batches_account', table_name='import_batches')
    op.drop_table('import_batches')
    # ### end Alembic commands ###
